package selfpi;

public enum SelfPiEvent {
	RED_BUTTON, 
	WHITE_BUTTON, 
	PRINT, 
	END_PRINTING, 
	HISTORY_SOUVERNIR_BUTTON, 
	HISTORY_WINNER_BUTTON, 
	HISTORY_DSLR_BUTTON,
	DSLR_IMPORT_BUTTON,
	RESET 
}
