package selfpi;

public enum SelfPiEvent {
	RED_BUTTON, 
	FACEBOOK_BUTTON,
	TWITTER_BUTTON,
	PRINT, 
	END_PRINTING,
	END_SHARING,
	HISTORY_SOUVERNIR_BUTTON, 
	HISTORY_PLAYER_BUTTON, 
	HISTORY_DSLR_BUTTON,
	DSLR_IMPORT_BUTTON,
	RESET 
}
