package selfpi;

public enum SelfpiState {
	IDLE_SOUVENIR, 
	TAKING_PICT, 
	PRINTING, 
	WAIT_FOR_SHARE, 
	POST_PROCESSING, 
	RE_PRINTING,
	TWEETING,
	FACEBOOK_UPLOAD,
	HISTORIC_SOUVENIR,
	HISTORIC_PLAYERS,
	HISTORIC_DSLR,
	IMPORT_DSLR
}
