package selfpi;

public enum SelfpiState {
	IDLE_SOUVENIR, 
	TAKING_PICT, 
	PRINTING, 
	WAIT_FOR_SHARE, 
	SHARING, 
	RE_PRINTING, 
	HISTORIC_SOUVENIR,
	HISTORIC_PLAYERS,
	HISTORIC_DSLR,
	IMPORT_DSLR
}
